name: build zenith
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:

# Add permissions block to explicitly grant package write access
permissions:
    contents: read
    packages: write
    id-token: write

jobs:
  push:
    name: "zenith_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - '3.0'
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./zenith
          file: ./zenith/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/McMelonTV/zenith_${{ matrix.tag }}
